DROP TABLE IF EXISTS GAME_DETAILS;
DROP TABLE IF EXISTS PLAYER;
DROP TABLE IF EXISTS GAME;

CREATE TABLE GAME (
  id INT AUTO_INCREMENT PRIMARY KEY,
  is_active VARCHAR(250) NOT NULL
);

CREATE TABLE GAME_DETAILS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  position VARCHAR(250) NOT NULL,
  count INT NOT NULL,
  game_id INT,
  FOREIGN KEY (game_id) REFERENCES GAME(id)
);

CREATE TABLE PLAYER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  user_name VARCHAR(250) NOT NULL,
  chance_flag VARCHAR(1) NOT NULL,
  game_id INT,
  FOREIGN KEY (game_id) REFERENCES GAME(id)
);